language: node_js
node_js:
  - "10"
install:
  - npm install
os:
  - linux
dist:
  - "lib"

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm version patch
        - npm publish

      deploy:
        provider: npm
        email: 1024540250@qq.com
        api_token: "$NPM_TOKEN"
